# 서버 설정
server:
  port: 8080  # 서버 포트


spring:
# DB 설정(MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/stockify?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: capstone!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet: # 파일 업로드 설정(이미지 첨부 등)
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail: # 로컬 테스트용(메일 테스트)
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: update   # 초기엔 update, 운영 시엔 validate 또는 none 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

 # JWT 관련 (예시용 키)
jwt:
  secret: stockjwt
  expiration: 3600000  # 1시간 (ms 단위)

# 로깅
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# ChatGPT API 키
openai:
  api:
    key: sk-xxxxxxx   # 네 실제 OpenAI API 키

